<?php
include_once "Shape.php";

class Triangle extends Shape
{
    public $color;
        public function __construct($side1, $side2, $side3,$color)
        {
            parent::__construct($side1, $side2, $side3);
            $this->color = $color;
        }
        public function setSide1($side1)
        {
            parent::setSide1($side1); // TODO: Change the autogenerated stub
        }
        public function setSide2($side2)
        {
            parent::setSide2($side2); // TODO: Change the autogenerated stub
        }
        public function setSide3($side3)
        {
            parent::setSide3($side3); // TODO: Change the autogenerated stub
        }
        public function getSide1()
        {
            return parent::getSide1(); // TODO: Change the autogenerated stub
        }
        public function getSide2()
        {
            return parent::getSide2(); // TODO: Change the autogenerated stub
        }
        public function getSide3()
        {
            return parent::getSide3(); // TODO: Change the autogenerated stub
        }
        public function getPerimeter(){
            return 1/2*($this->side1+$this->side2+$this->side3);
        }


    public function getArea(){

            return sqrt($this->getPerimeter()*(getPerimeter()-$this->side1)*(getPerimeter()-$this->side2)*(getPerimeter()-$this->side3));
        }
        public function toString(){
            echo "thong tin cua tam giac";
        }
}